name: Digital Ocean Deploy

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "main" ]

env:
  image_name: shoshin_tooling_backend:$(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image_name }}
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.3.0
      with:
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Login to Digital Ocean Registry
      run: doctl registry login --expiry-seconds 600

    - name: Push to Digital Ocean Registry
      run: docker push ${{ env.image_name }}